### ISSUE TITLE
Request- Content Box position - move whole box

### ISSUE THREAD

**Issue by Cix75** [trufanov-nok/scantailor-universal#105]
### Discussed in https://github.com/trufanov-nok/scantailor-universal/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **Cix75** January 18, 2022</sup>
Hello!
I just updated this nice, fantastic version of scantailor and I must say THANKS to the developers. It really help me each time.
I have two questions and I will try to explain the first one in this discussion.

Ones selected the content of a book/magazine and applied it on all pages (with the options menu) I will find the same dimension of the content box on all the pages as expected.

But, happens then that, for example, on a total of 200 pages it will not fit perfectly the content I really need on all pages (check the picture)
![2022-01-18_134017](https://user-images.githubusercontent.com/63376261/149940245-676f2fac-1f13-4cd2-bc6c-386f1363f12e.png)

so,I will need to adjust the border to set the right position.
The "Auto" option is not always precise and it also happens that some pixels of the characters or images are cut out, so I always do everything manually.

In another old version of scantailor there was a possibility of pressing the "SHIFT" key and, clicking on the content box, be able to move the whole box without changing its size and center it 'as is' on the necessary content.

There is this possibility here too maybe? 
if not, it could be really useful to have in one of the next releases, please.

Many thanks for what you can do and for your effort.
</div>

**Comment by trufanov-nok** [comment]
I already answered at discussions, so let's continue it there.
