### ISSUE TITLE
Request - Soft Text in Black & White

### ISSUE THREAD

**Issue by Cix75** [trufanov-nok/scantailor-universal#106]
### Discussed in https://github.com/trufanov-nok/scantailor-universal/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **Cix75** January 18, 2022</sup>
Hi, this is my second question... :p 
I will have to work on a lot of Magazines in color and a lot of books with pictures.
Just I noted that for the Text, using BW settings I really lost a lot of quality details of the image.
Using instead Grey/Color I have a bit more quality but I will not have a good white background sheet, it is always dirty compared to the BW one.
Using MIX, instead, I have the same result of the BW for the Text with color images good instead.
so the problem is almost on the text. There is a tool or some settings I can configure to have a result like the one in this picture, please?
![compare BW text](https://user-images.githubusercontent.com/63376261/149945068-e5e1d7cb-3b88-4f4a-a116-2f569d111237.png)

Here you can see a comparison image between the ScanDelay result and a clean using photoshop, I would like to keep a more softly text and not only a strong B&W, is there a way to obtain this result using ScanDelay maybe?
something like bilinear filtering on the B&W test pages. 
To obtain a similar result, usually, need to work pages in ScanTailor at 600dpi and then resize them in photoshop at 400dpi using bilinear soft filtering for each page.
So to have this possibility directly as an option in ScanTailor could really help me to save time, please :)

thanks for your help and effort :) W ScanTailor Universal!

</div>

**Comment by trufanov-nok** [comment]
I already answered at discussions, so let's continue it there.
