### ISSUE TITLE
Apply?

### ISSUE THREAD

**Issue by zvezdochiot** [trufanov-nok/scantailor-universal#108]
There is a need for an option: "Apply up to page [N]" in the choices.

**Comment by trufanov-nok** [comment]
I think "Edit/Select pages..." in menu and following "Apply to..." 's selected option should be enough.

**Comment by zvezdochiot** [comment]
Hi @trufanov-nok .

I'll try to adapt to "Edit/Select pages...". But its very inconvenient.
