### ISSUE TITLE
отсутствует тонкая настройка полей в слое иллюстраций

### ISSUE THREAD

**Issue by imamzade** [trufanov-nok/scantailor-universal#112]
Доброго времени суток!
Гифка с проблемой по [ссылке](https://ibb.co/3SCPxWb)

**Comment by trufanov-nok** [comment]
Добрый день,
Это - "выравнивание прямых", которое существует для того, что если человек щелкнет на ребро зоны и поставит новую вершину, отклонив её на пару пикселей от прямой, ему не пришлось бы ловить то минимальное отклонение обратно, чтобы удалить эту вершину и превратить ребро снова в прямую. По умолчанию ST удаляет вершины, которые отклоняют прямую меньше чем на 3 градуса и тем самым спрямляет прямые. Эта настройка не вынесена в UI, т.к. никто не просил, но я вынес её в файл настроек. Т.о. где-то на вашем компьютере лежит файл настроек с расширением ini, в который можно добавить  строки:
```
[zone_editor]
min_angle=1.0
```
к примеру, чтобы изменить отклонение с 3 до 1 градуса.
Где этот файл реально храниться можно посмотреть в меню Tools/Settings, наведя мышку на кнопку Defaults и подождав (не нажимая на кнопку) всплывающую подсказку. В разных операционных системах файл сохраняется в разных местах.

При случае я вынесу эту настройку в UI, чтобы не править файл настроек.

**Comment by imamzade** [comment]
Спасибо!
