### ISSUE TITLE
Новые функции

### ISSUE THREAD

**Issue by imamzade** [trufanov-nok/scantailor-universal#113]
Очень не хватает в слоях и зонах заливки возможности выделять не точечно нужный контур, а прямоугольником и эллипсом. Просто как идея, в случае, если возможно реализовать.

**Comment by trufanov-nok** [comment]
Если зажать Ctrl, то будет выделять прямоугольником. Если зажать Ctrl+Shift - то кругом, который потом можно растянуть в эллипс.

**Comment by imamzade** [comment]
Мое почтение! Спасибо за ваш труд!
