### ISSUE TITLE
debugging dlls are required

### ISSUE THREAD

**Issue by SilverGreen93** [trufanov-nok/scantailor-universal#135]
Hi, after installing latest release ([0.2.14](https://github.com/trufanov-nok/scantailor-universal/releases/tag/0.2.14)), 64bit, debugging dlls are required at application startup.
You must remove them from the final distribution and not distribute the Debug version, but the Release version:

```
---------------------------
scantailor-universal.exe - System Error
---------------------------
The code execution cannot proceed because MSVCP120D.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

Please update the release.
Thanks!

**Comment by trufanov-nok** [comment]
Thank you for report. 
Just updated 64bit version, please try again

**Comment by SilverGreen93** [comment]
It works now, thanks!
