### ISSUE TITLE
Bug: Preferences Window Expands Uncontrollably!

### ISSUE THREAD

**Issue by techana** [trufanov-nok/scantailor-universal#68]
App: ver. 0.2.7 build on 21/12/19
OS: macOS 10.15.1
Qt: ver. 5.13.2.

Once the Preferences window is opened, it keeps expanding from the right until it gets out of the computer' screen boundaries! This makes the user unable to access and modify the app's preferences.

Attached is a screen recoding of this bug.

Thank you.

![Screen-Recording-2019-12-21-at-12 27 50-PM_0](https://user-images.githubusercontent.com/10105658/71306455-a6c15500-23f1-11ea-8fcc-5047fb483223.gif)

**Comment by mara004** [comment]
I can confirm this issue with my (self-built) ScanTailor Universal on Linux.
App: `0.2.9 build on 24.11.20`
Platform: `KDE Neon 5.20.4`
Windowing System: `X11 1.20.8`
Qt: `5.15.2`
As a workaround, on Plasma, one can easily enforce a custom window size which solved the problem for me.

**Comment by trufanov-nok** [comment]
Reproducibility on Linux system is great. I have some guesses and will take a look tomorrow. But @mara004 I'll need your help to test the fix.

**Comment by mara004** [comment]
Okay, thanks, I'll try to test it

**Comment by trufanov-nok** [comment]
Well, now I can reproduce the problem by myself... (Qt 5.15.1) It happens if some of the settings are collapsed in settings tree and the `QTreeWidget` has `headerStretchLastSection=true` (by default) and `sizeAdjustPolicy=AdjustToContents` at the same time. This patch should fix it:
```
diff --git a/src/app/ui/SettingsDialog.ui b/src/app/ui/SettingsDialog.ui
index 5b1f2b65..fd066d1f 100644
--- a/src/app/ui/SettingsDialog.ui
+++ b/src/app/ui/SettingsDialog.ui
@@ -66,7 +66,7 @@
           <enum>QFrame::Raised</enum>
          </property>
          <property name="sizeAdjustPolicy">
-          <enum>QAbstractScrollArea::AdjustToContents</enum>
+          <enum>QAbstractScrollArea::AdjustToContentsOnFirstShow</enum>
          </property>
          <property name="editTriggers">
           <set>QAbstractItemView::NoEditTriggers</set>

```

Could you check?

**Comment by mara004** [comment]
Yep, fixed! Thank you!

**Comment by mara004** [comment]
![grafik](https://user-images.githubusercontent.com/65915611/101797813-ba862f80-3b0a-11eb-8bf6-f14a6cf1e176.png)
