### ISSUE TITLE
Bug: ScanTailor Quit Unexpectedly

### ISSUE THREAD

**Issue by techana** [trufanov-nok/scantailor-universal#69]
App: ver. 0.2.7 build on 21/12/19
OS: macOS 10.15.1
Qt: ver. 5.13.2.

In the Output stage, if "No despeckling" is chosen and the user clicks on "Despeckling" tab, then the app will crash.

Attached is a debug dump; notice "DespeckleView" lines.

Thank you
[ScanTailor_bump.txt](https://github.com/trufanov-nok/scantailor/files/3992207/ScanTailor_bump.txt)

**Comment by trufanov-nok** [comment]
Hi,
Thank you for your feedback! I have no Mac and possibility to test STU  on up to date Mac OS version.
Could you provide some additional info: was Debug mode (Settings/General/Debug mode) on or off during the crash? If it was on - then is this problem reproducible with debug mode off?

**Comment by techana** [comment]
Hi,
No, the Debug mode was not active during the crash. The attached dump above is the one given by the operating system.

**Comment by trufanov-nok** [comment]
I can't reproduce this with Qt 5.5 and OS X Mavericks 10.9.5 via virtual machine
I've build an up-to-date sources to dmg file https://github.com/trufanov-nok/scantailor/releases/download/0.2.8/ScanTailorUniversal-0.2.8.dmg
Could you try it? If it's ok, then it shall be something OS or Qt version specific.

**Comment by techana** [comment]
This version seems better. It didn't crash immediately when clicking on the Despeckling tab. It allowed me to navigate between tabs, enable/disable the despeckling and choose aggressiveness level. But then it suddenly crashes when going from Output tab to Despeckling tab!

**Comment by trufanov-nok** [comment]
Ok, let's try to bisect. Is it reproducible with https://github.com/trufanov-nok/scantailor/releases/download/0.2.3/ScanTailorUniversal-0.2.3.dmg ?
If it's so, does it page or image dependent? Perhaps dpi defendent? If so, i'll need the example image.
