### ISSUE TITLE
Support for hiDPI monitors - incorrect scaling

### ISSUE THREAD

**Issue by pbakes** [trufanov-nok/scantailor-universal#75]
The original scantailor works fine, but both scantailor-universal and scantailor-advanced don't scale properly on a hiDPI monitor setup (15" UHD laptop monitor & 32" 1440p monitor. On the laptop monitor the preview window is fine but all UI elements are hardly visible, and on the 32" UI elements are large and the preview window and thumbnail browser are completely blurred.

**Comment by trufanov-nok** [comment]
Hmm.. Could you provide a few screenshots? What are your laptop and monitor models? Could you specify your OS version? Have you used the binary STU/STA distributions or build them from sources? If the last - whats the Qt version used for that (STU's menu Help\About Qt)?

**Comment by pbakes** [comment]
I figured out a workaround. I used the $Env:QT_SCREEN_SCALE_FACTORS=1;1 in PowerShell before opening the program, and it now scales perfectly on both monitors.

**Comment by trufanov-nok** [comment]
Workaround isn't a solution.

**Comment by trufanov-nok** [comment]
It looks like Qt 6.x will introduce some changes in hiDPI monitors support so any additional settings for Qt5.x would be a waste of time. Closing this issue.
