### ISSUE TITLE
Feature request: Support JPEG 2000 input files

### ISSUE THREAD

**Issue by veikk0** [trufanov-nok/scantailor-universal#77]
As I understand it, JPEG 2000 isn't supported (or support is not enabled by default) by most FOSS software due to uncertainty/concern around patents. However, it would be useful to have a build-time option to enable JPEG 2000 input support so people who are able to build from source could enable it if they wanted. After making sure they're legally allowed to do so, of course.

While J2K is a relatively rare file format in the grand scheme of things, I imagine there are a number of people who use (or would like to use) ScanTailor-Universal to process public domain books distributed by the Internet Archive, as their uploaders often provide the original scanned and/or processed pages in the JPEG 2000 format. Processing these books is currently a bit of a PITA since it requires conversion of the .jp2 files to another format, and finding a conversion program that handles J2K can be a hassle in itself due to the aforementioned patent concerns.

The size of the converted files is another problem. If you want the conversion to be lossless (typically to TIFF or maybe PNG), the files are going to pretty big no matter what. I recently downloaded an almost 1000-page dictionary scan from the Internet Archive and converted the .jp2 files to TIFF (uncompressed, since that's what `opj_decompress` from the `libopenjp2-tools` package in Debian/Ubuntu outputs). The result: 25 GB of TIFF files, compared to the 800 MB of the .jp2 originals. Using GraphicsMagick the apply LZW compression to the converted files reduced them to 11 GB, but that's still a hefty amount for something that's ultimately still lossy (AFAIK the scans from Archive.org aren't using lossless J2K compression).

This conversion requirement also makes storing and backing up ScanTailor-Advanced projects like this more space-intensive than it needs to be. If I ever want to go back to such a project to change something, I need the converted files to be available. I could just delete the huge converted files and keep the .jp2 files, but that would require a re-conversion if I ever want re-open the project.

Thanks for the time you've put into this project btw. It's been very useful to me in creating efficiently compressed PDF files.

**Comment by trufanov-nok** [comment]
I have nothing against jp2 and it doesn't look like opensource can have any problems supporting it as I see jp2 support in GIMP (GPL) application via libopenjp2. The main concern is how many efforts it  requires to implement such support... Could you provide an jp2 image or link to it for tests?

**Comment by veikk0** [comment]
[Here's a link](https://ia802604.us.archive.org/view_archive.php?archive=/27/items/adventuresofsher00doylrich/adventuresofsher00doylrich_jp2.zip) to a collection of .jp2 images on Archive.org. You can also [download the entire archive](https://archive.org/download/adventuresofsher00doylrich/adventuresofsher00doylrich_jp2.zip) (194 MB).

I also recently noticed that the GIMP build included in Ubuntu 20.04 has JPEG 2000 support. It's probably a relatively recent development, since a few years ago there was basically zero support from any open-source application, or if there was it was disabled in the builds shipped by major Linux distributions (like the Debian/Ubuntu build of ImageMagick).

There's probably more support/interest now because JPEG 2000 turned 20 years old last year, so any patents relevant to the format (known or unknown) should have expired by now.

**Comment by trufanov-nok** [comment]
I've managed to add experimental jp2 support. It wasn't as easy as i hope.
Please check and test a code in the branch jp2: https://github.com/trufanov-nok/scantailor-universal/tree/jp2
Note the last commit comment in this branch: https://github.com/trufanov-nok/scantailor-universal/commit/b9a846a07348d4efbf11b77b039e3a2ea6a62310
Technically you just need to have libopenjp2-7-dev installed while executing `cmake ..` to enable jpeg 2000 support. Then you'll be able to see and choose *.jp2 files in open files dialog.

Unfortunately I couldn't find yet any grayscale or non RGB  jp2 image on web archive to test.

**Comment by silverbacknet** [comment]
Here are some that I just generated through the Photoshop filter, which isn't related to the open source filter so it should be a decent interaction test. I also used 256x256 tiles so you can test that. I wasn't exactly sure what you meant by non-RGB so I used CMYK; IIRC RGB files are internally YCbCr normally, unless color separation is specifically disabled. I have LuraWave and a few other applications with their own implementations as well if you want to try others.

[bucks-answering-machine-jp2-test.zip](https://github.com/trufanov-nok/scantailor-universal/files/6053413/bucks-answering-machine-jp2-test.zip)

**Comment by trufanov-nok** [comment]
@silverbacknet thanks! I've just tested them. So far so good.

**Comment by veikk0** [comment]
I've also tested it and it's working perfectly so far. My SSD and other storage devices thank you!

One thing I've noticed is that loading/displaying JPEG 2000 images is more CPU intensive and takes longer than other image types. I've noticed the same thing when opening J2K files with GIMP and Geeqie (image viewer), both of which use openjpeg for decoding. Maybe JPEG 2000 is just a more CPU intensive format, or it's a feature of the library. Could also be my 10-year-old, underclocked laptop CPU showing its age and making the difference more noticeable.

**Comment by silverbacknet** [comment]
Unfortunately, the only other comparable available free codec is LuraWave's, which is faster but also more buggy, and it has a proprietary redistribution license. There's a huge amount of room for optimization in openjpeg, both speed and quality, but it would also be a huge time commitment for a format that everyone has mostly lost interest in. The patent wars made it a niche format.

If you want loading speed, webp is probably a much better option. It's limited to 8-bit and raw compression isn't quite as much as jpeg2000, but it's *fast*.

I've personally moved on to HEIF/AVIF, which do have some critical mass, and decent support in the libheif library.

**Comment by trufanov-nok** [comment]
As far as I read while adding jp2 support - the JPEG 2000 is both more CPU intensive format and it's a feature of the library (which may be improved in future). To test CPU load and RAM usage you may refer to the package `libopenjp2-tools` which contains `opj_decompress` - a jp2 image converter that supports bmp/png as output: `opj_decompress -i image.j2k -o image.png`
It's based on libopenjp2 and a part of this project. There is a `-threads` option which is `ALL_CPUS` by default. So it may take all CPU cores to decompress. I saw this option in the library and left it by default. I guess it's `ALL_CPUS` too (the library isn't well documented). So I believe STU decompresses jp2 as fast as libopenjp2 lets it. I guess you still may affect default max number of threads that library may use in STU for jp2 decompression via environment variable `OPJ_NUM_THREADS` which isn't documented. Via execution of `OPJ_NUM_THREADS=2 ./scantailor-universal ` or something like that.
