### ISSUE TITLE
version 0.2.12 requires msvcr120d.dll(not msvcr120.dll)

### ISSUE THREAD

**Issue by john2545** [trufanov-nok/scantailor-universal#82]
version 0.2.12 
windows x64 version requires msvcr120d.dll(not msvcr120.dll) from Visual studio 2013 (not redistributable runtime)

**Comment by trufanov-nok** [comment]
Ok, looks like I've build the dependencies (libjpeg.dll etc.) for x64 in Debug mode. x32 is fine. Need to rebuild and update distributive.

**Comment by trufanov-nok** [comment]
Should be fixed now, please check.

**Comment by john2545** [comment]
> Should be fixed now, please check.

Thanks. It works fine.
