### ISSUE TITLE
Missing MSVCR120D.dll, VCOMP120.dll

### ISSUE THREAD

**Issue by Piolie** [trufanov-nok/scantailor-universal#87]
I wanted to try the latest release binary (0.2.12) of ST Universal but I'm getting a complaint that says `MSVCR120D.dll` is missing. I googled around and found that this DLL, with the `D` suffix, is intended for debugging purposes and cannot be redistributed. The suggested solution is to recompile the binary in release mode, or something like that.

This is for the 64 bit version on Windows 10 but it also fails on a Windows 7 VM. The 32bit version is also missing a DLL: `VCOMP120.dll`.

Thank you for your hard work on this wonderful project.

**Comment by silverbacknet** [comment]
Are you sure you have the latest? It was re-uploaded two weeks ago to fix that issue.

**Comment by trufanov-nok** [comment]
Hi,
Yes, it was reported https://github.com/trufanov-nok/scantailor-universal/issues/82 
And supposed to be fixed. But reporter didn't confirmed that. 
Perhaps you've got binary not from project's Release page: https://github.com/trufanov-nok/scantailor-universal/releases/tag/0.2.12 or the problem still exists which would be surprising. Try the latest binary and let me know if the problem still present.

**Comment by Piolie** [comment]
My apologies. I must have missed that issue. I've tried redownloading the latest release and it's working correctly.
