### ISSUE TITLE
'insert before" of multi-page tif uses wrong picture/page offsets

### ISSUE THREAD

**Issue by jjYBdx4IL** [trufanov-nok/scantailor-universal#92]
The saved project's xml file starts the inserted image sequence with fileImage=0. It should start with 1 - at least in my case, not sure if that's the same for all tif files.

    <image fileImage="0" fileId="777" id="778" subPages="1">
      <size width="1748" height="2480"/>
      <dpi vertical="300" horizontal="300"/>
    </image>

**Comment by trufanov-nok** [comment]
You mean whole your project is made from a single multipage tiff and you're inserting another page to it? And this page is a standalone file?

**Comment by jjYBdx4IL** [comment]
no, I mean "inserting a multi-page .tif". It starts referencing the inserted images starting from 0 instead of 1.

**Comment by trufanov-nok** [comment]
Should be fixed now in master branch

**Comment by jjYBdx4IL** [comment]
cool.ty.
