### ISSUE TITLE
Error building from source: Missing stylesheet

### ISSUE THREAD

**Issue by emwal** [trufanov-nok/scantailor-universal#94]
When building from source the following error message pops up and aborts the install, somehow I end up with a working copy of scantailor-universal anyway:

`Make Error at src/stylesheets/cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "/home/user/repositories/scantailor-universal/src/stylesheets/BreezeStyleSheets/Breeze":
  No such file or directory.
Call Stack (most recent call first):
  src/cmake_install.cmake:59 (include)
  cmake_install.cmake:71 (include)
`

I'm on Manjaro Linux.

**Comment by trufanov-nok** [comment]
You shall clone the project with all submodules it references:  
`git clone --recurse-submodules https://github.com/trufanov-nok/scantailor.git`

**Comment by emwal** [comment]
Right – it would be nice to add this to the wiki, since I couldn't find it anywhere/didn't see it, when installing for the first time.

Now it works without hiccups.
Thank you!

**Comment by trufanov-nok** [comment]
Have added `Getting sources` paragraph to wiki: https://github.com/trufanov-nok/scantailor-universal/wiki/Building-from-Source-Code-on-Linux-and-Mac-OS-X#getting-sources
